### ISSUE TITLE
App doesn't run smoothly

### ISSUE THREAD

**Issue by khuong291** [bilguunint/movieapp#1]
I ran the app on a simulator and checked out how much memory is taken up.
<img width="411" alt="Screen Shot 2020-07-10 at 10 22 43" src="https://user-images.githubusercontent.com/11523438/87112971-6e06a180-c297-11ea-874c-eb3884754bea.png">
It was around 230MB, which is very high.

**Comment by bilguunint** [comment]
Hey hi. Have you tried on real device with flutter run --release? It must be okey
